/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GFG */

#ifndef _Included_GFG
#define _Included_GFG
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GFG
 * Method:    print_Hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_GFG_print_1Hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
